version: '3.1'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: facegenerator_api
    ports:
      - 5000:5000
    volumes:
      - .:/api
    entrypoint: uvicorn --port 5000 --workers 1 --reload --log-level info --use-colors --host 0.0.0.0 face_generator:app
    network_mode: host