version: '3.1'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: facegenerator_api
    ports:
      - 3000:3000
    volumes:
      - .:/api
    entrypoint: uvicorn --root-path ${CONTEXT_PATH}  --host 0.0.0.0 --port 3000 --workers 1 --reload --log-level info --use-colors face_generator:app
    env_file:
      - .env
    environment:
      - PROJECT_PATH=
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512MB